name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Build BE
      run: node server.js
      working-directory: ./src/server
    - name: Build FE
      run: npm install
      working-directory: ./src
    - name: Build Playwright
      run: npm install -D @playwright/test
      working-directory: ./src
    - name: Run e2e tests
      run: npx playwright test tests
      working-directory: ./src
