name: Build Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: './src/package-lock.json'
    - name: Build FE
      run: npm install
      working-directory: ./src
    - name: Start FE
      run: npm run start-fe & # Run in the background
      working-directory: ./src  
    - name: Start BE
      run: npm run start-be & # Run in the background
      working-directory: ./src  
    - name: Build Playwright
      run: npx playwright install
    - name: Run e2e tests
      run: npm run test
      working-directory: ./src  

  deploy-backend:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Back-end
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_Backend_API_KEY }}    
      - name: Wait 60 sec
        run:  sleep 60

  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Back-end
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_Backend_API_KEY }}    