name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: './src/package-lock.json'
    - name: Build FE
      run: npm install
      working-directory: ./src
    - name: Start FE
      run: |
        cd ./src
        npm run start & # Run in the background
    - name: Start BE
      run: |
        cd ./src/server
        node server.js & # Run in the background
    - name: Build Playwright
      run: npx playwright install
    - name: Run e2e tests
      run: npx playwright test tests
      working-directory: ./src  
        